export const fullDeck = [
    { suit: "clubs", value: "A", img: "../images/cards/clubs_A.png" },
    { suit: "clubs", value: "2", img: "../images/cards/clubs_2.png" },
    { suit: "clubs", value: "3", img: "../images/cards/clubs_3.png" },
    { suit: "clubs", value: "4", img: "../images/cards/clubs_4.png" },
    { suit: "clubs", value: "5", img: "../images/cards/clubs_5.png" },
    { suit: "clubs", value: "6", img: "../images/cards/clubs_6.png" },
    { suit: "clubs", value: "7", img: "../images/cards/clubs_7.png" },
    { suit: "clubs", value: "8", img: "../images/cards/clubs_8.png" },
    { suit: "clubs", value: "9", img: "../images/cards/clubs_9.png" },
    { suit: "clubs", value: "10", img: "../images/cards/clubs_10.png" },
    { suit: "clubs", value: "J", img: "../images/cards/clubs_J.png" },
    { suit: "clubs", value: "Q", img: "../images/cards/clubs_Q.png" },
    { suit: "clubs", value: "K", img: "../images/cards/clubs_K.png" },

    { suit: "diamonds", value: "A", img: "../images/cards/diamonds_A.png" },
    { suit: "diamonds", value: "2", img: "../images/cards/diamonds_2.png" },
    { suit: "diamonds", value: "3", img: "../images/cards/diamonds_3.png" },
    { suit: "diamonds", value: "4", img: "../images/cards/diamonds_4.png" },
    { suit: "diamonds", value: "5", img: "../images/cards/diamonds_5.png" },
    { suit: "diamonds", value: "6", img: "../images/cards/diamonds_6.png" },
    { suit: "diamonds", value: "7", img: "../images/cards/diamonds_7.png" },
    { suit: "diamonds", value: "8", img: "../images/cards/diamonds_8.png" },
    { suit: "diamonds", value: "9", img: "../images/cards/diamonds_9.png" },
    { suit: "diamonds", value: "10", img: "../images/cards/diamonds_10.png" },
    { suit: "diamonds", value: "J", img: "../images/cards/diamonds_J.png" },
    { suit: "diamonds", value: "Q", img: "../images/cards/diamonds_Q.png" },
    { suit: "diamonds", value: "K", img: "../images/cards/diamonds_K.png" },

    { suit: "hearts", value: "A", img: "../images/cards/hearts_A.png" },
    { suit: "hearts", value: "2", img: "../images/cards/hearts_2.png" },
    { suit: "hearts", value: "3", img: "../images/cards/hearts_3.png" },
    { suit: "hearts", value: "4", img: "../images/cards/hearts_4.png" },
    { suit: "hearts", value: "5", img: "../images/cards/hearts_5.png" },
    { suit: "hearts", value: "6", img: "../images/cards/hearts_6.png" },
    { suit: "hearts", value: "7", img: "../images/cards/hearts_7.png" },
    { suit: "hearts", value: "8", img: "../images/cards/hearts_8.png" },
    { suit: "hearts", value: "9", img: "../images/cards/hearts_9.png" },
    { suit: "hearts", value: "10", img: "../images/cards/hearts_10.png" },
    { suit: "hearts", value: "J", img: "../images/cards/hearts_J.png" },
    { suit: "hearts", value: "Q", img: "../images/cards/hearts_Q.png" },
    { suit: "hearts", value: "K", img: "../images/cards/hearts_K.png" },

    { suit: "spades", value: "A", img: "../images/cards/spades_A.png" },
    { suit: "spades", value: "2", img: "../images/cards/spades_2.png" },
    { suit: "spades", value: "3", img: "../images/cards/spades_3.png" },
    { suit: "spades", value: "4", img: "../images/cards/spades_4.png" },
    { suit: "spades", value: "5", img: "../images/cards/spades_5.png" },
    { suit: "spades", value: "6", img: "../images/cards/spades_6.png" },
    { suit: "spades", value: "7", img: "../images/cards/spades_7.png" },
    { suit: "spades", value: "8", img: "../images/cards/spades_8.png" },
    { suit: "spades", value: "9", img: "../images/cards/spades_9.png" },
    { suit: "spades", value: "10", img: "../images/cards/spades_10.png" },
    { suit: "spades", value: "J", img: "../images/cards/spades_J.png" },
    { suit: "spades", value: "Q", img: "../images/cards/spades_Q.png" },
    { suit: "spades", value: "K", img: "../images/cards/spades_K.png" }
];
