export const fullDeck = [
    { suit: "clubs", value: "A", img: "../images/clubs_A.png" },
    { suit: "clubs", value: "2", img: "../images/clubs_2.png" },
    { suit: "clubs", value: "3", img: "../images/clubs_3.png" },
    { suit: "clubs", value: "4", img: "../images/clubs_4.png" },
    { suit: "clubs", value: "5", img: "../images/clubs_5.png" },
    { suit: "clubs", value: "6", img: "../images/clubs_6.png" },
    { suit: "clubs", value: "7", img: "../images/clubs_7.png" },
    { suit: "clubs", value: "8", img: "../images/clubs_8.png" },
    { suit: "clubs", value: "9", img: "../images/clubs_9.png" },
    { suit: "clubs", value: "10", img: "../images/clubs_10.png" },
    { suit: "clubs", value: "J", img: "../images/clubs_J.png" },
    { suit: "clubs", value: "Q", img: "../images/clubs_Q.png" },
    { suit: "clubs", value: "K", img: "../images/clubs_K.png" },

    { suit: "diamonds", value: "A", img: "../images/diamonds_A.png" },
    { suit: "diamonds", value: "2", img: "../images/diamonds_2.png" },
    { suit: "diamonds", value: "3", img: "../images/diamonds_3.png" },
    { suit: "diamonds", value: "4", img: "../images/diamonds_4.png" },
    { suit: "diamonds", value: "5", img: "../images/diamonds_5.png" },
    { suit: "diamonds", value: "6", img: "../images/diamonds_6.png" },
    { suit: "diamonds", value: "7", img: "../images/diamonds_7.png" },
    { suit: "diamonds", value: "8", img: "../images/diamonds_8.png" },
    { suit: "diamonds", value: "9", img: "../images/diamonds_9.png" },
    { suit: "diamonds", value: "10", img: "../images/diamonds_10.png" },
    { suit: "diamonds", value: "J", img: "../images/diamonds_J.png" },
    { suit: "diamonds", value: "Q", img: "../images/diamonds_Q.png" },
    { suit: "diamonds", value: "K", img: "../images/diamonds_K.png" },

    { suit: "hearts", value: "A", img: "../images/hearts_A.png" },
    { suit: "hearts", value: "2", img: "../images/hearts_2.png" },
    { suit: "hearts", value: "3", img: "../images/hearts_3.png" },
    { suit: "hearts", value: "4", img: "../images/hearts_4.png" },
    { suit: "hearts", value: "5", img: "../images/hearts_5.png" },
    { suit: "hearts", value: "6", img: "../images/hearts_6.png" },
    { suit: "hearts", value: "7", img: "../images/hearts_7.png" },
    { suit: "hearts", value: "8", img: "../images/hearts_8.png" },
    { suit: "hearts", value: "9", img: "../images/hearts_9.png" },
    { suit: "hearts", value: "10", img: "../images/hearts_10.png" },
    { suit: "hearts", value: "J", img: "../images/hearts_J.png" },
    { suit: "hearts", value: "Q", img: "../images/hearts_Q.png" },
    { suit: "hearts", value: "K", img: "../images/hearts_K.png" },

    { suit: "spades", value: "A", img: "../images/spades_A.png" },
    { suit: "spades", value: "2", img: "../images/spades_2.png" },
    { suit: "spades", value: "3", img: "../images/spades_3.png" },
    { suit: "spades", value: "4", img: "../images/spades_4.png" },
    { suit: "spades", value: "5", img: "../images/spades_5.png" },
    { suit: "spades", value: "6", img: "../images/spades_6.png" },
    { suit: "spades", value: "7", img: "../images/spades_7.png" },
    { suit: "spades", value: "8", img: "../images/spades_8.png" },
    { suit: "spades", value: "9", img: "../images/spades_9.png" },
    { suit: "spades", value: "10", img: "../images/spades_10.png" },
    { suit: "spades", value: "J", img: "../images/spades_J.png" },
    { suit: "spades", value: "Q", img: "../images/spades_Q.png" },
    { suit: "spades", value: "K", img: "../images/spades_K.png" }
];
